# Stage 1: Build React app
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build  # outputs to /app/dist

# Stage 2: Nginx to serve frontend
FROM nginx:stable-alpine
# Copy built files
COPY --from=builder /app/dist /usr/share/nginx/html
# Copy Nginx config
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

# Run Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]






































