# BUILD STAGE
FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


# PRODUCTION STAGE 
FROM node:22-alpine
WORKDIR /app

COPY ./package.json ./
RUN npm install --omit=dev   

COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
EXPOSE 2000

CMD ["node", "dist/index.js"]
