# ---- BUILD STAGE ----
FROM node:22-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


# ---- PRODUCTION STAGE ----
FROM node:22-alpine AS production
WORKDIR /app

# Only copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Copy built JS files from builder stage
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
EXPOSE 2000

CMD ["node", "dist/index.js"]
