# Dev Dockerfile
FROM node:22-alpine

WORKDIR /app


COPY package*.json ./
RUN npm install


COPY . .


EXPOSE 2000


CMD ["npx", "nodemon", "--watch", "src", "--ext", "ts", "--exec", "ts-node", "src/index.ts"]